# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres:10.4-alpine
    container_name: kafka-nodejs-example-database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
    expose:
      - "5432"
    ports:
      - 5432:5432
    volumes:
      - ./services/database/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./services/database/seed.sql:/docker-entrypoint-initdb.d/2-seed.sql
  
